M48
; DRILL file {KiCad 9.0.7} date 2026-02-27T16:16:51-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-27T16:16:51-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.020
%
G90
G05
T1
X107.302Y-104.48
X107.302Y-108.48
T2
X104.49Y-111.455
X104.49Y-117.805
M30
