import { Style } from "../style.slint";

export component Datetime inherits HorizontalLayout {
    in property <image> icon;
    in property <string> date;
    in property <string> time;
    in property <string> meridiem;

    alignment: center;

    VerticalLayout {
        alignment: center;
        
        Image {
            source: icon;
            width: 80px;
            height: 80px;
        }
    }

    VerticalLayout {
        alignment: center;
        padding-left: 10px;

        Text {
            text: time + " " + meridiem;
            font-size: 45pt;
            font-family: Style.default-font-family;
        }

        HorizontalLayout {
            padding-left: 5px;
            
            Text {
                text: date;
                font-size: 25pt;
                font-family: Style.default-font-family;
            }
        }
    }
}
