import { Style } from "../style.slint";

export global DatetimeAdapter {
    in property <int> hour12: 0;
    in property <int> minute: 0;
    in property <string> meridiem: "--";
    in property <string> date: "loading...";

    public pure function time() -> string {
        let datetime = self.meridiem == "--" ? "--:--" : self.hour12 + ":" + self.minute;
        return datetime + " " + self.meridiem;
    }

    public pure function icon() -> image {
        let sun = @image-url("../assets/icons/sun.svg");
        let moon = @image-url("../assets/icons/moon.svg");

        if (self.hour12 >= 6) {
            return self.meridiem == "AM" ? sun : moon;
        }

        return self.meridiem == "PM" ? sun : moon;
    }
}

export component Datetime inherits HorizontalLayout {
    in property <string> date: DatetimeAdapter.date;
    in property <string> time: DatetimeAdapter.time();
    in property <image> icon: DatetimeAdapter.icon();

    alignment: center;

    VerticalLayout {
        alignment: center;
        
        Image {
            source: icon;
            width: 80px;
            height: 80px;
        }
    }

    VerticalLayout {
        alignment: center;
        padding-left: 10px;

        Text {
            text: time;                
            font-size: 45pt;
            font-family: Style.default-font-family;
        }

        HorizontalLayout {
            padding-left: 5px;
            
            Text {
                text: date;
                font-size: 25pt;
                font-family: Style.default-font-family;
            }
        }
    }
}
