import { Style } from "../style.slint";


export global UsageAdapter {
    in property <[percent]> cpus_usage;
    in property <percent> memory_usage;
    in property <percent> swap_usage;
}


export component UsageBar inherits HorizontalLayout {
    in property <string> label;
    in property <color> value-color;
    in property <percent> value;
    in property <length> radius;

    alignment: center;
    spacing: 20px;

    Text {
        text: label;
        font-size: 20pt;
        font-family: Style.default-font-family;
        color: Style.theme.text;
    }

    Rectangle {
        height: 22px;
        width: 70%;
        background: Style.theme.background;
        border-color: value-color;
        border-radius: radius;
        border-width: 3px;
        clip: true;

        Rectangle {
            x: 0;
            background: value-color;
            width: value;
            height: parent.height;
            border-radius: radius;
        }
    }
}

export component CpuUsage inherits VerticalLayout {
    spacing: Style.default-spacing;

    for usage[index] in UsageAdapter.cpus_usage: UsageBar {
        label: "CPU " + index + ":";
        value-color: Style.theme.bar-1;
        radius: 10px;
        value: usage;
    }
}

export component MemoryUsage inherits VerticalLayout {
    spacing: Style.default-spacing;

    property <[{label: string, value: percent}]> data: [
        {label: "MEM:", value: UsageAdapter.memory_usage },
        {label: "SWP:", value: UsageAdapter.swap_usage },
    ];

    for usage in data: UsageBar {
        label: usage.label;
        value-color: Style.theme.bar-2;
        radius: 6px;
        value: usage.value;
    }
}
